export const BADGE_DEFINITIONS = [
  {
    slug: 'first_log',
    name: 'Premier pas',
    description: 'Premier jour complété',
    icon: '🌱',
    condition_type: 'total_done',
    condition_value: 1,
  },
  {
    slug: 'streak_3',
    name: '3 jours',
    description: '3 jours consécutifs',
    icon: '🔥',
    condition_type: 'streak_days',
    condition_value: 3,
  },
  {
    slug: 'streak_7',
    name: '1 semaine',
    description: '7 jours consécutifs',
    icon: '⚡',
    condition_type: 'streak_days',
    condition_value: 7,
  },
  {
    slug: 'streak_14',
    name: '2 semaines',
    description: '14 jours consécutifs',
    icon: '💪',
    condition_type: 'streak_days',
    condition_value: 14,
  },
  {
    slug: 'streak_30',
    name: '1 mois',
    description: '30 jours consécutifs',
    icon: '🏆',
    condition_type: 'streak_days',
    condition_value: 30,
  },
  {
    slug: 'streak_50',
    name: '50 jours',
    description: '50 jours consécutifs',
    icon: '🌟',
    condition_type: 'streak_days',
    condition_value: 50,
  },
  {
    slug: 'streak_100',
    name: 'Centenaire',
    description: '100 jours consécutifs',
    icon: '💎',
    condition_type: 'streak_days',
    condition_value: 100,
  },
  {
    slug: 'perfect_week',
    name: 'Semaine parfaite',
    description: '7 jours consécutifs complétés',
    icon: '✨',
    condition_type: 'perfect_week',
    condition_value: 7,
  },
  {
    slug: 'total_100',
    name: 'Centurion',
    description: '100 jours complétés au total',
    icon: '🎖️',
    condition_type: 'total_done',
    condition_value: 100,
  },
];
