// Objectifs prédéfinis que l'utilisateur peut sélectionner
export const OBJECTIVE_TEMPLATES = [
  {
    slug: 'no_smoking',
    name: 'Ne pas fumer',
    icon: '🚭',
    type: 'quantifiable',
    unit: 'cigarettes',
    positive_goal: false, // "ne pas faire"
    description: 'Réduire ou arrêter de fumer',
    color: '#EF4444',
  },
  {
    slug: 'no_alcohol',
    name: 'Ne pas boire',
    icon: '🚱',
    type: 'quantifiable',
    unit: 'verres',
    positive_goal: false,
    description: 'Réduire ou arrêter la consommation d\'alcool',
    color: '#F59E0B',
  },
  {
    slug: 'sport',
    name: 'Faire du sport',
    icon: '🏃',
    type: 'binary',
    unit: null,
    positive_goal: true,
    description: 'Pratiquer une activité physique',
    color: '#22C55E',
  },
  {
    slug: 'meditation',
    name: 'Méditer',
    icon: '🧘',
    type: 'binary',
    unit: null,
    positive_goal: true,
    description: 'Pratiquer la méditation ou la pleine conscience',
    color: '#8B5CF6',
  },
  {
    slug: 'reading',
    name: 'Lire',
    icon: '📚',
    type: 'quantifiable',
    unit: 'pages',
    positive_goal: true,
    description: 'Lire chaque jour',
    color: '#3B82F6',
  },
  {
    slug: 'sleep_early',
    name: 'Dormir tôt',
    icon: '🌙',
    type: 'binary',
    unit: null,
    positive_goal: true,
    description: 'Se coucher à une heure raisonnable',
    color: '#6366F1',
  },
  {
    slug: 'no_junk_food',
    name: 'Pas de junk food',
    icon: '🥗',
    type: 'binary',
    unit: null,
    positive_goal: false,
    description: 'Éviter la malbouffe',
    color: '#EC4899',
  },
  {
    slug: 'hydration',
    name: 'Boire de l\'eau',
    icon: '💧',
    type: 'quantifiable',
    unit: 'litres',
    positive_goal: true,
    description: 'Rester bien hydraté',
    color: '#06B6D4',
  },
];

export const OBJECTIVE_COLORS = [
  '#2D5BE3', '#22C55E', '#EF4444', '#F59E0B',
  '#8B5CF6', '#EC4899', '#06B6D4', '#6366F1',
  '#14B8A6', '#F97316', '#84CC16', '#A855F7',
];
